name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Deno
        # You may pin to the exact commit or the version.
        # uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        uses: denoland/setup-deno@v1.1.2
        
      - name: Build step
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "light-crow-18"
          entrypoint: "https://deno.land/std@0.188.0/http/file_server.ts" # 📝 Update the entrypoint
          root: "dist"
